### ISSUE TITLE
How to run a multi-party set intersection？

### ISSUE THREAD

**Issue by lushimeng** [jellevos/threshold-multiparty-psi#3]
Hello, I have used make to compile a executable file. How can I allow the intersection of multiple privacy collections? For example, specify the collection size, etc.

![}AUG{1FU3URWS{V G6%_JO0](https://github.com/jellevos/threshold-multiparty-psi/assets/64461623/f52c58f3-00dc-44a8-8c14-64f4f776b814)

**Comment by jellevos** [comment]
If you check out `main.cpp` you'll see that the default operation is to hardcode a few sets and then perform some benchmarks on them using functions from `benchmarking.cpp`. You'd have to modify this main file to execute the experiments the way you like them.

I do agree that it would be nice to have something like a command line interface for this. I am currently not able to make those changes, but I can refer you to [another repository](https://github.com/jellevos/private-logic-and-mpso), which essentially implements a more efficient version of the MPSI protocol in this repository. That one does have a command line interface. :)
